spring.application.name=deployment-config-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/dcm_db
spring.datasource.username=dcm_user
spring.datasource.password=dcm_password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true